### ISSUE TITLE
線形入力コマンド / AutoCADとBRICSCADで結果が異なる

### ISSUE THREAD

**Issue by Takaku-Kenji** [ZukenAlfatech/shinkouran#2]
お疲れさまです。Quocです。

I am checking commands of 新高欄.

線形入力コマンド (RL_LineInput):

-	AutoCAD 2019: there is a bug.
![acad-NG](https://user-images.githubusercontent.com/56807607/98783305-b3e99700-243c-11eb-8fff-79ceafa5e5cb.png)
-	BricsCAD V18: Ok.
![bcad-OK](https://user-images.githubusercontent.com/56807607/98783331-bcda6880-243c-11eb-978f-c7afaee1a86a.png)

＃測点マークが表示されない不具合です

**Comment by Takaku-Kenji** [comment]
I fixed the following bugs that I mentioned in previous emails:
Bug info:

1.線形入力コマンド (RL_LineInput):
Modified:
OLD: 
              bool bRet = SmcCreateBlockBegin( m_strBlkName, 2 );

NEW: 
              bool bRet = SmcCreateBlockBegin(m_strBlkName, 0);

2.線形編集コマンド (RL_LineEdit), 高さ編集コマンド (RL_HeightEdit):
Added code after create TEXT object:

OLD:
              oText.Create(en1);

NEW:
              oText.Create(en1);
              acedRedraw(en1, 1);

SneCreateStructure.arx         2.0.0.62 1.0.0.1   2020/11/12  19:31:10
CreateStructure.zlx                 2.0.0.62 1.0.0.1   2020/11/12  19:35:02

修正モジュールを下記にコピーしました。
・Customers\し\新高欄\TestIN\Program Files\Alfatech

**Comment by zat-kimnguyen** [comment]
測点マークが表示されることを確認しました。
承認します。

承認ファイルはApprovedへ移動済みです。
